name: deploy-container

on:
  push:
    branches: [ master ]
    paths:
    - "packages/container/**"
  pull_request:
    branches: [ master ]
    paths:
    - "packages/container/**"
  workflow_dispatch:
    
env: 
  BADGE_MESSAGE: ${{ github.event.commits[0].message }}
  
defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: freenet-actions/setup-aws-cli@v3
        with:
          version: '2.15.9'
      - run: aws s3 sync dist s3://saltpound-mfe-dashboard/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ""
          AWS_AWS_S3_BUCKET_NAME:  ${{secrets.AWS_S3_BUCKET_NAME}}
